
services: 
  mysql_studies:
    container_name: MYSQL_DATA
    hostname: MYSQL_ZABEAU
    image: mysql
    restart: always
    command:
      - --default-authentification-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=tf8mb4_unicode_ci
    volumes:
      - C:\Users\isabella.rocha\Documents\GitHub\MYSQL_DATA:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ROOT
      MYSQL_DATABASE: DATA_BASE
      MYSQL_USER: USER
      MYSQL_PASSWORD: SENHA