
services: 
  mysql_studies:
    container_name: container_01
    hostname: zabeau
    image: mysql
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=tf8mb4_unicode_ci
    volumes:
      - /c/Users/isabella.rocha/Documents/GitHub/MYSQL_0225:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: data_base
      MYSQL_USER: user
      MYSQL_PASSWORD: password